[package]
name = "tag_dict_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
quick-xml = "0.27.1"
chrono = "0.4.23"
whoami = "1.3.0"